[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "opensolution"
authors = [{name = "OpenSolution", email = "soporte@opensolution.com.mx"}]
dynamic = ["version", "description"]
